services:
  trace-table-manager-front:
    container_name: container-my-trace-table-manager
    build:
      context: .
    restart: always
    ports:
      - "8888:80"
    networks:
      - tracetable-network
    env_file:
      - .env

networks:
  tracetable-network:
    name: tracetable-network
    driver: bridge
    external: true